name: Mirror Bitbucket Repositories to Gitea

on:
  schedule:
    - cron: '0 0 * * *'  # Запускать каждый день в полночь
  workflow_dispatch:  # Позволяет запускать workflow вручную через интерфейс Gitea

jobs:
  mirror-bitbucket:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
      # Шаг 1: Проверка кода
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Установка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Указываем версию Python

      # Шаг 3: Установка зависимостей (если они есть)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Если используются сторонние библиотеки

      # Шаг 4: Запуск скрипта
      - name: Run Bitbucket to Gitea mirror script
        env:
          BITBUCKET_USERNAME: ${{ secrets.BITBUCKET_USERNAME }}
          BITBUCKET_APP_PASSWORD: ${{ secrets.BITBUCKET_APP_PASSWORD }}
          BITBUCKET_TARGET_USERNAME: ${{ secrets.BITBUCKET_TARGET_USERNAME }}
          GITEA_URL: ${{ secrets.URL }}
          GITEA_TOKEN: ${{ secrets.TOKEN }}
          GITEA_ORG_NAME: ${{ secrets.ORG_NAME_FOR_BITBUCKET }}
        run: |
          python3 bitbucket_to_gitea_mirror.py  # Замените на имя вашего скрипта

