name: Mirroring Bitbucket Repositories to Gitea

on:
  schedule:
    - cron: '0 0 * * *'  # Запускать каждый день в полночь
  workflow_dispatch:  # Позволяет запускать workflow вручную через интерфейс Gitea

jobs:
  mirroring-bitbucket:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
      # Шаг 1: Проверка кода
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Установка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Указываем версию Python

      # Шаг 3: Установка зависимостей (если они есть)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Если используются сторонние библиотеки

      # Шаг 4: Запуск скрипта
      - name: Run Bitbucket to Gitea mirror script
        env:
          BITBUCKET_USERNAME: ${{ secrets.USERNAME_BITBUCKET }}
          BITBUCKET_APP_PASSWORD: ${{ secrets.APP_PASSWORD_BITBUCKET }}
          BITBUCKET_TARGET_USERNAME: ${{ secrets.TARGET_USERNAME_BITBUCKET }}
          GITEA_URL: ${{ vars.URL_GITEA }}
          GITEA_TOKEN: ${{ secrets.TOKEN_GITEA }}
          GITEA_ORG_NAME: ${{ vars.ORG_NAME_FOR_BITBUCKET }}
        run: |
          python3 bitbucket_to_gitea_mirror.py  # Замените на имя вашего скрипта

  notify:
    runs-on: ubuntu-latest
    needs: mirroring-bitbucket  # Зависит от завершения задачи "mirroring-bitbucket"
    if: failure()  # Запускается только при ошибке в задаче "mirroring-bitbucket"
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.yandex.ru  # Адрес SMTP-сервера Yandex
          server_port: 465  # Порт SMTP (465 для SSL, 587 для TLS)
          username: ${{ secrets.SMTP_USERNAME }}  # Логин SMTP
          password: ${{ secrets.SMTP_PASSWORD }}  # Пароль SMTP
          subject: "Workflow Failed: ${{ gitea.workflow }}"
          body: |
            The workflow "${{ gitea.workflow }}" has failed.
            Please check the logs: ${{ gitea.server_url }}/${{ gitea.repository }}/actions/runs/${{ gitea.run_id }}
          to: ${{ secrets.EMAIL_TO }}  # Получатель письма
          from: '"Gitea Notifications" <${{ secrets.SMTP_USERNAME }}>'  # Отправитель письма (экранировано)
          content_type: text/html  # Формат письма (text/plain или text/html)

