name: Mirror GitHub Repositories to Gitea

on:
  schedule:
    - cron: '0 0 * * *'  # Запускать каждый день в полночь
  workflow_dispatch:  # Позволяет запускать workflow вручную через интерфейс Gitea

jobs:
  mirror-repositories:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
      # Шаг 1: Проверка кода
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Установка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Указываем версию Python

      # Шаг 3: Установка зависимостей (если они есть)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Если используются сторонние библиотеки

      # Шаг 4: Запуск скрипта
      - name: Run GitHub to Gitea mirror script
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          GITHUB_TARGET_USERNAME: ${{ secrets.TARGET_USERNAME_GITHUB }}
          GITEA_URL: ${{ secrets.URL }}  # URL вашего сервера Gitea
          GITEA_TOKEN: ${{ secrets.TOKEN }}
          GITEA_ORG_NAME: ${{ secrets.ORG_NAME_FOR_GITHUB }}
        run: |
          python3 github_to_gitea_mirror.py  # Замените на имя вашего скрипта

