name: Mirroring GitHub Repositories to Gitea

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight
  workflow_dispatch:  # Allows manual triggering of the workflow via the Gitea interface

jobs:
  mirroring-github:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify Python version

      # Step 3: Install dependencies (if any)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # If third-party libraries are used

      # Step 4: Run the GitHub to Gitea mirror script
      - name: Run GitHub to Gitea mirror script
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          GITHUB_TARGET_USERNAME: ${{ secrets.TARGET_USERNAME_GITHUB }}
          GITEA_URL: ${{ vars.URL_GITEA }}  # URL of your Gitea server
          GITEA_TOKEN: ${{ secrets.TOKEN_GITEA }}
          GITEA_ORG_NAME: ${{ vars.ORG_NAME_FOR_GITHUB }}
        run: |
          python3 github_to_gitea_mirror.py  # Replace with your script name

  notify:
    runs-on: ubuntu-latest
    needs: mirroring-github  # Depends on the completion of the "mirroring-github" job
    if: failure()  # Runs only if the "mirroring-github" job fails
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.yandex.ru  # Yandex SMTP server address
          server_port: 465  # SMTP port (465 for SSL, 587 for TLS)
          username: ${{ secrets.SMTP_USERNAME }}  # SMTP username
          password: ${{ secrets.SMTP_PASSWORD }}  # SMTP password
          subject: "Workflow Failed: ${{ gitea.workflow }}"
          body: |
            The workflow "${{ gitea.workflow }}" has failed.
            Please check the logs: ${{ gitea.server_url }}/${{ gitea.repository }}/actions/runs/${{ gitea.run_id }}
          to: ${{ secrets.EMAIL_TO }}  # Email recipient
          from: '"Gitea Notifications" <${{ secrets.SMTP_USERNAME }}>'  # Email sender (escaped)
          content_type: text/html  # Email format (text/plain or text/html)

