name: CI Workflow with Email Notifications
on:
  workflow_dispatch:  # Запускается вручную через интерфейс Gitea

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          echo "Running tests..."
          exit 1  # Имитация ошибки

  notify:
    runs-on: ubuntu-latest
    needs: build  # Зависит от завершения задачи "build"
    if: failure()  # Запускается только при ошибке в задаче "build"
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.yandex.ru  # Адрес SMTP-сервера Yandex
          server_port: 465  # Порт SMTP (465 для SSL, 587 для TLS)
          username: ${{ secrets.SMTP_USERNAME }}  # Логин SMTP
          password: ${{ secrets.SMTP_PASSWORD }}  # Пароль SMTP
          subject: "Workflow Failed: ${{ gitea.workflow }}"
          body: |
            The workflow "${{ gitea.workflow }}" has failed.
            Please check the logs: ${{ gitea.server_url }}/${{ gitea.repository }}/actions/runs/${{ gitea.run_id }}
          to: ${{ secrets.EMAIL_TO }}  # Получатель письма
          from: '"Gitea Notifications" <${{ secrets.SMTP_USERNAME }}>'  # Отправитель письма (экранировано)
          content_type: text/html  # Формат письма (text/plain или text/html)

